import Foundation

/// Bounds for the Large & Old Files feature. This is deliberately separate from
/// DeletionSafetyPolicy because these are personal files, not cache files.
enum LargeFileScanPolicy {
    nonisolated static func scanRoots(home: URL) -> [URL] {
        [
            home.appendingPathComponent("Documents", isDirectory: true),
            home.appendingPathComponent("Desktop", isDirectory: true),
            home.appendingPathComponent("Downloads", isDirectory: true),
            home.appendingPathComponent("Movies", isDirectory: true),
            home.appendingPathComponent("Music", isDirectory: true),
            home.appendingPathComponent("Pictures", isDirectory: true)
        ]
    }

    /// Managed libraries and bundles we never descend into or offer for deletion.
    nonisolated static let excludedFolderNames: Set<String> = [
        "Photos Library.photoslibrary",
        "Photo Booth Library",
        "iMovie Library.imovielibrary",
        "iMovie Theater.theater",
        "TV Library.tvlibrary",
        "Music Library.musiclibrary",
        "GarageBand"
    ]

    /// Dependency and build folders that belong to a project, not to the person
    /// using the Mac. Large Files is for things you downloaded or made — videos,
    /// disk images, archives, models. A checked-out `node_modules` binary is not
    /// a file anyone chose to keep, and Dev Projects already offers these folders
    /// whole, where deleting them actually means something. Listing their
    /// contents here individually is noise.
    ///
    /// Hidden variants (`.build`, `.gradle`, `.venv`, `.next`, …) need no entry:
    /// the scan skips hidden files and the dot-prefix rule below catches them.
    nonisolated static let projectArtifactFolderNames: Set<String> = [
        "node_modules",
        "bower_components",
        "Pods",
        "Carthage",
        "DerivedData",
        "vendor",
        "venv",
        "__pycache__",
        "site-packages",
        "target",
        // Build output. `build` is the big one: Xcode writes
        // `build/SourcePackages/repositories/…` (bare git repos full of large
        // .pack files) and Gradle writes `build/intermediates/…` (stripped .so
        // libraries and source maps). Everything under it is regenerated by the
        // next build.
        "build",
        "Build",
        "SourcePackages",
        "intermediates",
        "dist",
        "out"
    ]

    nonisolated static func isExcludedDirectory(_ url: URL) -> Bool {
        let name = url.lastPathComponent
        if name.hasPrefix(".") { return true }
        if excludedFolderNames.contains(name) { return true }
        if projectArtifactFolderNames.contains(name) { return true }
        let ext = url.pathExtension.lowercased()
        return ["app", "photoslibrary", "imovielibrary", "tvlibrary", "musiclibrary", "theater", "bundle"].contains(ext)
    }

    nonisolated static func isInsideExcludedDirectory(_ url: URL) -> Bool {
        let components = url.standardizedFileURL.pathComponents.dropLast()
        for component in components {
            if component.hasPrefix(".") { return true }
            if excludedFolderNames.contains(component) { return true }
            if projectArtifactFolderNames.contains(component) { return true }
            let ext = (component as NSString).pathExtension.lowercased()
            if ["app", "photoslibrary", "imovielibrary", "tvlibrary", "musiclibrary", "theater", "bundle"].contains(ext) {
                return true
            }
        }
        return false
    }

    /// A file may be deleted only if it is a regular file under one of the scan
    /// roots and nowhere near Library or system locations.
    nonisolated static func isEligibleForDeletion(_ url: URL) -> Bool {
        let fm = FileManager.default
        let std = url.standardizedFileURL
        let path = std.path

        var isDir: ObjCBool = false
        guard fm.fileExists(atPath: path, isDirectory: &isDir), !isDir.boolValue else { return false }
        if path.contains("/Library/") { return false }
        if isInsideExcludedDirectory(std) { return false }

        let home = fm.homeDirectoryForCurrentUser
        return scanRoots(home: home).contains { root in
            path.hasPrefix(root.standardizedFileURL.path + "/")
        }
    }
}
